burningwheelrolls/urls.py
from django.urls import path

from . import views

app_name = "burningwheelrolls"

urlpatterns = [
    path("roll_dice/", views.roll_dice, name="roll_dice"),
    path("roll_luck/", views.roll_luck, name="roll_luck"),
    path("assess_difficulty/", views.assess_difficulty, name="assess_difficulty"),
]

gmemulator/urls.py
from django.urls import path

from . import views

app_name = "gmemulator"

urlpatterns = [
    path("fate-question", views.fate_question, name="fate_question"),
]

mythic/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("gm-emulator", include("gmemulator.urls")),
    path("burning-wheel", include("burningwheelrolls.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- boostrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- local CSS -->
    {% load static %}
     <link rel="stylesheet" href="{% static 'generators/styles.css' %}">
        <title>{% block title %}Django GM Emulator {% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👺</text></svg>">
    <meta name="robots" content="noindex">
</head>

<body class="d-flex flex-column min-vh-100">


    {% block navbar %}


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                    role="button" aria-haspopup="true" aria-expanded="false">Fate
                    </a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'gmemulator:fate_question' %}">Ask a Fate Question</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                    role="button" aria-haspopup="true" aria-expanded="false">Burning Wheel
                    </a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'burningwheelrolls:roll_dice' %}">Roll Dice</a>
                    <a class="dropdown-item" href="{% url 'burningwheelrolls:assess_difficulty' %}">Assess Difficulty</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <br>

    {% endblock %}
    <div class="container">
    {% block messages %}
        {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">{{ message }}</div>
                {% endfor %}

        {% endif %}
    {% endblock %}

        {% block content %}{% endblock %}

    </div>


    <!-- Jquery and Popper-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>


    <!-- Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>



</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
Mythic GM Emulator
{% endblock title %}


{% block content %}
<h1>Mythic GM Emulator</h1>
<p>This is a pet project to implement the Mythic GM Emulator in the django framework.</p>
{% endblock content %}